
version: '2.1'

services:
  dbbackup:
    environment:
      # Postgres environment variable
      # Can be set to execute PG tools directly
      - PGHOST=db
      - PGUSER=docker
      - PGPASSWORD=docker
      - PGPORT=5432
